// Auto-generated by generate-stickers.js
export const stickers = {
  "Acheron": [
    "/stickers/Organized_Stickers/Acheron/Acheron 1.png",
    "/stickers/Organized_Stickers/Acheron/Acheron 2.png",
    "/stickers/Organized_Stickers/Acheron/Acheron 3.png",
    "/stickers/Organized_Stickers/Acheron/Acheron 4.png"
  ],
  "Argenti": [
    "/stickers/Organized_Stickers/Argenti/Argenti 1.png",
    "/stickers/Organized_Stickers/Argenti/Argenti 2.png",
    "/stickers/Organized_Stickers/Argenti/Argenti 3.png",
    "/stickers/Organized_Stickers/Argenti/Argenti 4.png"
  ],
  "Arlan": [
    "/stickers/Organized_Stickers/Arlan/1_Arlan.png",
    "/stickers/Organized_Stickers/Arlan/Arlan.png"
  ],
  "Asta": [
    "/stickers/Organized_Stickers/Asta/2_Asta.png",
    "/stickers/Organized_Stickers/Asta/Asta.png"
  ],
  "Aventurine": [
    "/stickers/Organized_Stickers/Aventurine/Aventurine 1.png",
    "/stickers/Organized_Stickers/Aventurine/Aventurine 2.png",
    "/stickers/Organized_Stickers/Aventurine/Aventurine 3.png",
    "/stickers/Organized_Stickers/Aventurine/Aventurine 4.png"
  ],
  "Bailu": [
    "/stickers/Organized_Stickers/Bailu/Bailu 1.png",
    "/stickers/Organized_Stickers/Bailu/Bailu 2.png",
    "/stickers/Organized_Stickers/Bailu/Bailu.png",
    "/stickers/Organized_Stickers/Bailu/Pom-Pom Gallery - Finest Duel Under the Pristine Blue Set 16_Bailu.png"
  ],
  "Black Swan": [
    "/stickers/Organized_Stickers/Black Swan/Black Swan 1.png",
    "/stickers/Organized_Stickers/Black Swan/Black Swan 2.png",
    "/stickers/Organized_Stickers/Black Swan/Black Swan 3.png",
    "/stickers/Organized_Stickers/Black Swan/Black Swan 4.png"
  ],
  "Blade": [
    "/stickers/Organized_Stickers/Blade/Blade 1.png",
    "/stickers/Organized_Stickers/Blade/Blade 2.png",
    "/stickers/Organized_Stickers/Blade/Blade 3.png",
    "/stickers/Organized_Stickers/Blade/Blade 4.png",
    "/stickers/Organized_Stickers/Blade/Blade.png"
  ],
  "Boothill": [
    "/stickers/Organized_Stickers/Boothill/Boothill 1.png",
    "/stickers/Organized_Stickers/Boothill/Boothill 2.png",
    "/stickers/Organized_Stickers/Boothill/Boothill 3.png",
    "/stickers/Organized_Stickers/Boothill/Boothill 4.png",
    "/stickers/Organized_Stickers/Boothill/Pom-Pom Gallery｜Then Wake to Weep Stickers_Boothill 1.png",
    "/stickers/Organized_Stickers/Boothill/Pom-Pom Gallery｜Then Wake to Weep Stickers_Boothill 2.png"
  ],
  "Bronya": [
    "/stickers/Organized_Stickers/Bronya/Bronya.png"
  ],
  "Carmella": [
    "/stickers/Organized_Stickers/Carmella/Carmella.png"
  ],
  "Cheers": [
    "/stickers/Organized_Stickers/Cheers/Cheers.png"
  ],
  "Clara": [
    "/stickers/Organized_Stickers/Clara/9_Clara.png"
  ],
  "Clockie": [
    "/stickers/Organized_Stickers/Clockie/Clockie.png",
    "/stickers/Organized_Stickers/Clockie/Pom-Pom Gallery _ If One Dreams At Midnight_Clockie.png"
  ],
  "Critter": [
    "/stickers/Organized_Stickers/Critter/Critter.png"
  ],
  "Cycrane": [
    "/stickers/Organized_Stickers/Cycrane/Cycrane.png"
  ],
  "Dan Heng": [
    "/stickers/Organized_Stickers/Dan Heng/3_Danheng.png",
    "/stickers/Organized_Stickers/Dan Heng/Dan Heng.png"
  ],
  "Dan Heng Imbibitor Lunae": [
    "/stickers/Organized_Stickers/Dan Heng Imbibitor Lunae/Dan Heng Imbibitor Lunae 1.png",
    "/stickers/Organized_Stickers/Dan Heng Imbibitor Lunae/Dan Heng Imbibitor Lunae 2.png",
    "/stickers/Organized_Stickers/Dan Heng Imbibitor Lunae/Dan Heng Imbibitor Lunae 3.png",
    "/stickers/Organized_Stickers/Dan Heng Imbibitor Lunae/Dan Heng Imbibitor Lunae 4.png"
  ],
  "Dr. Ratio": [
    "/stickers/Organized_Stickers/Dr. Ratio/Dr. Ratio 1.png",
    "/stickers/Organized_Stickers/Dr. Ratio/Dr. Ratio 2.png",
    "/stickers/Organized_Stickers/Dr. Ratio/Dr. Ratio 3.png",
    "/stickers/Organized_Stickers/Dr. Ratio/Dr. Ratio 4.png"
  ],
  "Dreamjolt Troupe - Mr. Domescreen": [
    "/stickers/Organized_Stickers/Dreamjolt Troupe - Mr. Domescreen/Dreamjolt Troupe - Mr. Domescreen.png"
  ],
  "Feixiao": [
    "/stickers/Organized_Stickers/Feixiao/Feixiao 1.png",
    "/stickers/Organized_Stickers/Feixiao/Feixiao 2.png",
    "/stickers/Organized_Stickers/Feixiao/Feixiao 3.png",
    "/stickers/Organized_Stickers/Feixiao/Feixiao 4.png"
  ],
  "Feixiao Inner Beast": [
    "/stickers/Organized_Stickers/Feixiao Inner Beast/Feixiao Inner Beast.png"
  ],
  "Firefly": [
    "/stickers/Organized_Stickers/Firefly/Firefly 1.png",
    "/stickers/Organized_Stickers/Firefly/Firefly 2.png",
    "/stickers/Organized_Stickers/Firefly/Firefly 3.png",
    "/stickers/Organized_Stickers/Firefly/Firefly 4.png"
  ],
  "Fu Xuan": [
    "/stickers/Organized_Stickers/Fu Xuan/Fu Xuan 1.png",
    "/stickers/Organized_Stickers/Fu Xuan/Fu Xuan 2.png",
    "/stickers/Organized_Stickers/Fu Xuan/Fu Xuan 3.png",
    "/stickers/Organized_Stickers/Fu Xuan/Fu Xuan 4.png"
  ],
  "Fuyuan": [
    "/stickers/Organized_Stickers/Fuyuan/Fuyuan.png"
  ],
  "Gallagher": [
    "/stickers/Organized_Stickers/Gallagher/Gallagher 1.png",
    "/stickers/Organized_Stickers/Gallagher/Gallagher 2.png",
    "/stickers/Organized_Stickers/Gallagher/Gallagher 3.png"
  ],
  "General Huaiyan": [
    "/stickers/Organized_Stickers/General Huaiyan/General Huaiyan.png"
  ],
  "Gepard": [
    "/stickers/Organized_Stickers/Gepard/7_Gepard.png",
    "/stickers/Organized_Stickers/Gepard/Gepard.png"
  ],
  "Guinaifen": [
    "/stickers/Organized_Stickers/Guinaifen/Guinaifen 1.png",
    "/stickers/Organized_Stickers/Guinaifen/Guinaifen 2.png",
    "/stickers/Organized_Stickers/Guinaifen/Guinaifen 3.png",
    "/stickers/Organized_Stickers/Guinaifen/Pom-Pom Gallery _ Jolted Awake From a Winter Dream_Guinaifen 1.png",
    "/stickers/Organized_Stickers/Guinaifen/Pom-Pom Gallery _ Jolted Awake From a Winter Dream_Guinaifen 2.png"
  ],
  "Hanu": [
    "/stickers/Organized_Stickers/Hanu/Hanu.png"
  ],
  "Hanya": [
    "/stickers/Organized_Stickers/Hanya/Hanya 1.png",
    "/stickers/Organized_Stickers/Hanya/Hanya 2.png",
    "/stickers/Organized_Stickers/Hanya/Hanya 3.png"
  ],
  "Herta": [
    "/stickers/Organized_Stickers/Herta/4_Herta.png",
    "/stickers/Organized_Stickers/Herta/Herta.png",
    "/stickers/Organized_Stickers/Herta/Pom-Pom Gallery _ Crown of the Mundane and Divine_Herta.png"
  ],
  "Himeko": [
    "/stickers/Organized_Stickers/Himeko/6_Himeko.png",
    "/stickers/Organized_Stickers/Himeko/Himeko.png"
  ],
  "Hook": [
    "/stickers/Organized_Stickers/Hook/5_Hook.png",
    "/stickers/Organized_Stickers/Hook/Hook.png"
  ],
  "Huohuo": [
    "/stickers/Organized_Stickers/Huohuo/Huohuo 1.png",
    "/stickers/Organized_Stickers/Huohuo/Huohuo 2.png",
    "/stickers/Organized_Stickers/Huohuo/Huohuo 3.png",
    "/stickers/Organized_Stickers/Huohuo/Huohuo 4.png"
  ],
  "Huohuo (Tail)": [
    "/stickers/Organized_Stickers/Huohuo (Tail)/Tail.png"
  ],
  "Jade": [
    "/stickers/Organized_Stickers/Jade/Jade 1.png",
    "/stickers/Organized_Stickers/Jade/Jade 2.png",
    "/stickers/Organized_Stickers/Jade/Jade 3.png",
    "/stickers/Organized_Stickers/Jade/Jade 4.png"
  ],
  "Jiaoqiu": [
    "/stickers/Organized_Stickers/Jiaoqiu/Jiaoqiu 1.png",
    "/stickers/Organized_Stickers/Jiaoqiu/Jiaoqiu 2.png",
    "/stickers/Organized_Stickers/Jiaoqiu/Jiaoqiu 3.png",
    "/stickers/Organized_Stickers/Jiaoqiu/Jiaoqiu 4.png"
  ],
  "Jing Yuan": [
    "/stickers/Organized_Stickers/Jing Yuan/Jing Yuan 1.png",
    "/stickers/Organized_Stickers/Jing Yuan/Jing Yuan 2.png"
  ],
  "Jingliu": [
    "/stickers/Organized_Stickers/Jingliu/Jingliu 1.png",
    "/stickers/Organized_Stickers/Jingliu/Jingliu 2.png",
    "/stickers/Organized_Stickers/Jingliu/Jingliu 3.png",
    "/stickers/Organized_Stickers/Jingliu/Jingliu 4.png"
  ],
  "Kafka": [
    "/stickers/Organized_Stickers/Kafka/8_Kafka.png",
    "/stickers/Organized_Stickers/Kafka/Kafka 1.png",
    "/stickers/Organized_Stickers/Kafka/Kafka 2.png",
    "/stickers/Organized_Stickers/Kafka/Kafka 3.png",
    "/stickers/Organized_Stickers/Kafka/Kafka 4.png"
  ],
  "Kakavasha": [
    "/stickers/Organized_Stickers/Kakavasha/Kakavasha.png"
  ],
  "Lingsha": [
    "/stickers/Organized_Stickers/Lingsha/Lingsha 1.png",
    "/stickers/Organized_Stickers/Lingsha/Lingsha 2.png",
    "/stickers/Organized_Stickers/Lingsha/Lingsha 3.png",
    "/stickers/Organized_Stickers/Lingsha/Lingsha 4.png"
  ],
  "Luka": [
    "/stickers/Organized_Stickers/Luka/Luka 1.png",
    "/stickers/Organized_Stickers/Luka/Luka 2.png",
    "/stickers/Organized_Stickers/Luka/Luka 3.png"
  ],
  "Luocha": [
    "/stickers/Organized_Stickers/Luocha/Luocha.png"
  ],
  "Lynx": [
    "/stickers/Organized_Stickers/Lynx/Lynx 1.png",
    "/stickers/Organized_Stickers/Lynx/Lynx 2.png",
    "/stickers/Organized_Stickers/Lynx/Lynx 3.png"
  ],
  "March 7th": [
    "/stickers/Organized_Stickers/March 7th/March 7th 1.png",
    "/stickers/Organized_Stickers/March 7th/March 7th 2.png",
    "/stickers/Organized_Stickers/March 7th/March 7th 3.png",
    "/stickers/Organized_Stickers/March 7th/March 7th.png",
    "/stickers/Organized_Stickers/March 7th/March 7th_1.png",
    "/stickers/Organized_Stickers/March 7th/March 7th_10.png",
    "/stickers/Organized_Stickers/March 7th/March 7th_11.png",
    "/stickers/Organized_Stickers/March 7th/March 7th_12.png",
    "/stickers/Organized_Stickers/March 7th/March 7th_13.png",
    "/stickers/Organized_Stickers/March 7th/March 7th_14.png",
    "/stickers/Organized_Stickers/March 7th/March 7th_15.png",
    "/stickers/Organized_Stickers/March 7th/March 7th_16.png",
    "/stickers/Organized_Stickers/March 7th/March 7th_2.png",
    "/stickers/Organized_Stickers/March 7th/March 7th_3.png",
    "/stickers/Organized_Stickers/March 7th/March 7th_4.png",
    "/stickers/Organized_Stickers/March 7th/March 7th_5.png",
    "/stickers/Organized_Stickers/March 7th/March 7th_6.png",
    "/stickers/Organized_Stickers/March 7th/March 7th_7.png",
    "/stickers/Organized_Stickers/March 7th/March 7th_8.png",
    "/stickers/Organized_Stickers/March 7th/March 7th_9.png"
  ],
  "Mikhail": [
    "/stickers/Organized_Stickers/Mikhail/Mikhail.png"
  ],
  "Misha": [
    "/stickers/Organized_Stickers/Misha/Misha 1.png",
    "/stickers/Organized_Stickers/Misha/Misha 2.png",
    "/stickers/Organized_Stickers/Misha/Misha 3.png"
  ],
  "Moze": [
    "/stickers/Organized_Stickers/Moze/Moze 1.png",
    "/stickers/Organized_Stickers/Moze/Moze 2.png",
    "/stickers/Organized_Stickers/Moze/Moze 3.png"
  ],
  "Mr. Reca": [
    "/stickers/Organized_Stickers/Mr. Reca/Mr. Reca.png"
  ],
  "Natasha": [
    "/stickers/Organized_Stickers/Natasha/Natasha.png"
  ],
  "Origami Bird": [
    "/stickers/Organized_Stickers/Origami Bird/Origami Bird.png"
  ],
  "Other": [
    "/stickers/Organized_Stickers/Other/Other.png"
  ],
  "Pela": [
    "/stickers/Organized_Stickers/Pela/12_Pela.png",
    "/stickers/Organized_Stickers/Pela/Pela.png"
  ],
  "Peppy": [
    "/stickers/Organized_Stickers/Peppy/Peppy.png"
  ],
  "Pom-Pom": [
    "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 1.png",
    "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 10.png",
    "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 2.png",
    "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 3.png",
    "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 4.png",
    "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 5.png",
    "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 6.png",
    "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 7.png",
    "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 8.png",
    "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 9.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 1.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 10.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 11.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 12.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 13.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 14.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 15.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 16.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 2.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 3.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 4.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 5.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 6.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 7.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 8.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 9.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom Stickers Set 1_Pom-Pom 1.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom Stickers Set 1_Pom-Pom 2.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom Stickers Set 1_Pom-Pom 3.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom Stickers Set 1_Pom-Pom 4.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom Stickers Set 1_Pom-Pom 5.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom Stickers Set 1_Pom-Pom 6.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom Stickers Set 1_Pom-Pom 7.png",
    "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom.png"
  ],
  "Qing Que": [
    "/stickers/Organized_Stickers/Qing Que/Qing Que.png",
    "/stickers/Organized_Stickers/Qing Que/Qingque.png"
  ],
  "Raccoon": [
    "/stickers/Organized_Stickers/Raccoon/Raccoon 1.png",
    "/stickers/Organized_Stickers/Raccoon/Raccoon 2.png",
    "/stickers/Organized_Stickers/Raccoon/Raccoon 3.png"
  ],
  "Rappa": [
    "/stickers/Organized_Stickers/Rappa/Rappa 1.png",
    "/stickers/Organized_Stickers/Rappa/Rappa 2.png",
    "/stickers/Organized_Stickers/Rappa/Rappa 3.png",
    "/stickers/Organized_Stickers/Rappa/Rappa 4.png"
  ],
  "Robin": [
    "/stickers/Organized_Stickers/Robin/Robin 1.png",
    "/stickers/Organized_Stickers/Robin/Robin 2.png",
    "/stickers/Organized_Stickers/Robin/Robin 3.png",
    "/stickers/Organized_Stickers/Robin/Robin 4.png",
    "/stickers/Organized_Stickers/Robin/Robin.png"
  ],
  "Ruan Mei": [
    "/stickers/Organized_Stickers/Ruan Mei/Ruan Mei 1.png",
    "/stickers/Organized_Stickers/Ruan Mei/Ruan Mei 2.png",
    "/stickers/Organized_Stickers/Ruan Mei/Ruan Mei 3.png",
    "/stickers/Organized_Stickers/Ruan Mei/Ruan Mei 4.png"
  ],
  "Sampo": [
    "/stickers/Organized_Stickers/Sampo/13_Sampo.png",
    "/stickers/Organized_Stickers/Sampo/Pom-Pom Gallery _ If One Dreams At Midnight_Sampo.png",
    "/stickers/Organized_Stickers/Sampo/Pom-Pom Gallery _ Jolted Awake From a Winter Dream_Sampo.png",
    "/stickers/Organized_Stickers/Sampo/Sampo.png"
  ],
  "Screwllum": [
    "/stickers/Organized_Stickers/Screwllum/Screwllum.png"
  ],
  "Serval": [
    "/stickers/Organized_Stickers/Serval/15_Serval.png",
    "/stickers/Organized_Stickers/Serval/Serval.png"
  ],
  "Silver Wolf": [
    "/stickers/Organized_Stickers/Silver Wolf/16_Silver Wolf.png"
  ],
  "Slumbernana Monkey": [
    "/stickers/Organized_Stickers/Slumbernana Monkey/Slumbernana Monkey 1.png",
    "/stickers/Organized_Stickers/Slumbernana Monkey/Slumbernana Monkey 2.png",
    "/stickers/Organized_Stickers/Slumbernana Monkey/Slumbernana Monkey 3.png"
  ],
  "Sparkle": [
    "/stickers/Organized_Stickers/Sparkle/Pom-Pom Gallery _ If One Dreams At Midnight_Sparkle 1.png",
    "/stickers/Organized_Stickers/Sparkle/Pom-Pom Gallery _ If One Dreams At Midnight_Sparkle 2.png",
    "/stickers/Organized_Stickers/Sparkle/Sparkle 1.png",
    "/stickers/Organized_Stickers/Sparkle/Sparkle 2.png",
    "/stickers/Organized_Stickers/Sparkle/Sparkle 3.png",
    "/stickers/Organized_Stickers/Sparkle/Sparkle 4.png"
  ],
  "Stelle Harmony": [
    "/stickers/Organized_Stickers/Stelle Harmony/Stelle Harmony.png"
  ],
  "Sunday": [
    "/stickers/Organized_Stickers/Sunday/Sunday.png"
  ],
  "Sushang": [
    "/stickers/Organized_Stickers/Sushang/Pom-Pom Gallery - Finest Duel Under the Pristine Blue Set 16_Sushang.png",
    "/stickers/Organized_Stickers/Sushang/Pom-Pom Gallery _ Jolted Awake From a Winter Dream_Sushang.png",
    "/stickers/Organized_Stickers/Sushang/Pom-Pom Gallery_ Final Closed Beta_Sushang.png",
    "/stickers/Organized_Stickers/Sushang/Sushang.png"
  ],
  "Talisman": [
    "/stickers/Organized_Stickers/Talisman/Talisman.png"
  ],
  "Tingyun": [
    "/stickers/Organized_Stickers/Tingyun/Pom-Pom Gallery_ Final Closed Beta_Tingyun.png",
    "/stickers/Organized_Stickers/Tingyun/Tingyun.png"
  ],
  "Topaz": [
    "/stickers/Organized_Stickers/Topaz/Topaz 1.png",
    "/stickers/Organized_Stickers/Topaz/Topaz 2.png",
    "/stickers/Organized_Stickers/Topaz/Topaz 3.png",
    "/stickers/Organized_Stickers/Topaz/Topaz 4.png",
    "/stickers/Organized_Stickers/Topaz/Topaz.png"
  ],
  "Trailblazer (Caelus)": [
    "/stickers/Organized_Stickers/Trailblazer (Caelus)/10_Male MC.png",
    "/stickers/Organized_Stickers/Trailblazer (Caelus)/Caelus.png",
    "/stickers/Organized_Stickers/Trailblazer (Caelus)/Trailblazer_male.png"
  ],
  "Trailblazer (Stelle)": [
    "/stickers/Organized_Stickers/Trailblazer (Stelle)/11_Female MC.png",
    "/stickers/Organized_Stickers/Trailblazer (Stelle)/Stelle.png",
    "/stickers/Organized_Stickers/Trailblazer (Stelle)/Trailblazer_female.png"
  ],
  "Trash Can": [
    "/stickers/Organized_Stickers/Trash Can/Trash Can.png"
  ],
  "Tuskpir": [
    "/stickers/Organized_Stickers/Tuskpir/Tuskpir.png"
  ],
  "Welt": [
    "/stickers/Organized_Stickers/Welt/14_Welt.png",
    "/stickers/Organized_Stickers/Welt/Welt.png"
  ],
  "Xueyi": [
    "/stickers/Organized_Stickers/Xueyi/Xueyi 1.png",
    "/stickers/Organized_Stickers/Xueyi/Xueyi 2.png",
    "/stickers/Organized_Stickers/Xueyi/Xueyi 3.png"
  ],
  "Yanqing": [
    "/stickers/Organized_Stickers/Yanqing/Yanqing 1.png",
    "/stickers/Organized_Stickers/Yanqing/Yanqing 2.png",
    "/stickers/Organized_Stickers/Yanqing/Yanqing.png"
  ],
  "Young Jing Yuan": [
    "/stickers/Organized_Stickers/Young Jing Yuan/Young Jing Yuan.png"
  ],
  "Yukong": [
    "/stickers/Organized_Stickers/Yukong/Pom-Pom Gallery_ Final Closed Beta_Yukong.png",
    "/stickers/Organized_Stickers/Yukong/Yukong.png"
  ],
  "Yunli": [
    "/stickers/Organized_Stickers/Yunli/Yunli 1.png",
    "/stickers/Organized_Stickers/Yunli/Yunli 2.png",
    "/stickers/Organized_Stickers/Yunli/Yunli 3.png",
    "/stickers/Organized_Stickers/Yunli/Yunli 4.png"
  ]
};

export const allStickerPaths = [
  "/stickers/Organized_Stickers/Acheron/Acheron 1.png",
  "/stickers/Organized_Stickers/Acheron/Acheron 2.png",
  "/stickers/Organized_Stickers/Acheron/Acheron 3.png",
  "/stickers/Organized_Stickers/Acheron/Acheron 4.png",
  "/stickers/Organized_Stickers/Argenti/Argenti 1.png",
  "/stickers/Organized_Stickers/Argenti/Argenti 2.png",
  "/stickers/Organized_Stickers/Argenti/Argenti 3.png",
  "/stickers/Organized_Stickers/Argenti/Argenti 4.png",
  "/stickers/Organized_Stickers/Arlan/1_Arlan.png",
  "/stickers/Organized_Stickers/Arlan/Arlan.png",
  "/stickers/Organized_Stickers/Asta/2_Asta.png",
  "/stickers/Organized_Stickers/Asta/Asta.png",
  "/stickers/Organized_Stickers/Aventurine/Aventurine 1.png",
  "/stickers/Organized_Stickers/Aventurine/Aventurine 2.png",
  "/stickers/Organized_Stickers/Aventurine/Aventurine 3.png",
  "/stickers/Organized_Stickers/Aventurine/Aventurine 4.png",
  "/stickers/Organized_Stickers/Bailu/Bailu 1.png",
  "/stickers/Organized_Stickers/Bailu/Bailu 2.png",
  "/stickers/Organized_Stickers/Bailu/Bailu.png",
  "/stickers/Organized_Stickers/Bailu/Pom-Pom Gallery - Finest Duel Under the Pristine Blue Set 16_Bailu.png",
  "/stickers/Organized_Stickers/Black Swan/Black Swan 1.png",
  "/stickers/Organized_Stickers/Black Swan/Black Swan 2.png",
  "/stickers/Organized_Stickers/Black Swan/Black Swan 3.png",
  "/stickers/Organized_Stickers/Black Swan/Black Swan 4.png",
  "/stickers/Organized_Stickers/Blade/Blade 1.png",
  "/stickers/Organized_Stickers/Blade/Blade 2.png",
  "/stickers/Organized_Stickers/Blade/Blade 3.png",
  "/stickers/Organized_Stickers/Blade/Blade 4.png",
  "/stickers/Organized_Stickers/Blade/Blade.png",
  "/stickers/Organized_Stickers/Boothill/Boothill 1.png",
  "/stickers/Organized_Stickers/Boothill/Boothill 2.png",
  "/stickers/Organized_Stickers/Boothill/Boothill 3.png",
  "/stickers/Organized_Stickers/Boothill/Boothill 4.png",
  "/stickers/Organized_Stickers/Boothill/Pom-Pom Gallery｜Then Wake to Weep Stickers_Boothill 1.png",
  "/stickers/Organized_Stickers/Boothill/Pom-Pom Gallery｜Then Wake to Weep Stickers_Boothill 2.png",
  "/stickers/Organized_Stickers/Bronya/Bronya.png",
  "/stickers/Organized_Stickers/Carmella/Carmella.png",
  "/stickers/Organized_Stickers/Cheers/Cheers.png",
  "/stickers/Organized_Stickers/Clara/9_Clara.png",
  "/stickers/Organized_Stickers/Clockie/Clockie.png",
  "/stickers/Organized_Stickers/Clockie/Pom-Pom Gallery _ If One Dreams At Midnight_Clockie.png",
  "/stickers/Organized_Stickers/Critter/Critter.png",
  "/stickers/Organized_Stickers/Cycrane/Cycrane.png",
  "/stickers/Organized_Stickers/Dan Heng/3_Danheng.png",
  "/stickers/Organized_Stickers/Dan Heng/Dan Heng.png",
  "/stickers/Organized_Stickers/Dan Heng Imbibitor Lunae/Dan Heng Imbibitor Lunae 1.png",
  "/stickers/Organized_Stickers/Dan Heng Imbibitor Lunae/Dan Heng Imbibitor Lunae 2.png",
  "/stickers/Organized_Stickers/Dan Heng Imbibitor Lunae/Dan Heng Imbibitor Lunae 3.png",
  "/stickers/Organized_Stickers/Dan Heng Imbibitor Lunae/Dan Heng Imbibitor Lunae 4.png",
  "/stickers/Organized_Stickers/Dr. Ratio/Dr. Ratio 1.png",
  "/stickers/Organized_Stickers/Dr. Ratio/Dr. Ratio 2.png",
  "/stickers/Organized_Stickers/Dr. Ratio/Dr. Ratio 3.png",
  "/stickers/Organized_Stickers/Dr. Ratio/Dr. Ratio 4.png",
  "/stickers/Organized_Stickers/Dreamjolt Troupe - Mr. Domescreen/Dreamjolt Troupe - Mr. Domescreen.png",
  "/stickers/Organized_Stickers/Feixiao/Feixiao 1.png",
  "/stickers/Organized_Stickers/Feixiao/Feixiao 2.png",
  "/stickers/Organized_Stickers/Feixiao/Feixiao 3.png",
  "/stickers/Organized_Stickers/Feixiao/Feixiao 4.png",
  "/stickers/Organized_Stickers/Feixiao Inner Beast/Feixiao Inner Beast.png",
  "/stickers/Organized_Stickers/Firefly/Firefly 1.png",
  "/stickers/Organized_Stickers/Firefly/Firefly 2.png",
  "/stickers/Organized_Stickers/Firefly/Firefly 3.png",
  "/stickers/Organized_Stickers/Firefly/Firefly 4.png",
  "/stickers/Organized_Stickers/Fu Xuan/Fu Xuan 1.png",
  "/stickers/Organized_Stickers/Fu Xuan/Fu Xuan 2.png",
  "/stickers/Organized_Stickers/Fu Xuan/Fu Xuan 3.png",
  "/stickers/Organized_Stickers/Fu Xuan/Fu Xuan 4.png",
  "/stickers/Organized_Stickers/Fuyuan/Fuyuan.png",
  "/stickers/Organized_Stickers/Gallagher/Gallagher 1.png",
  "/stickers/Organized_Stickers/Gallagher/Gallagher 2.png",
  "/stickers/Organized_Stickers/Gallagher/Gallagher 3.png",
  "/stickers/Organized_Stickers/General Huaiyan/General Huaiyan.png",
  "/stickers/Organized_Stickers/Gepard/7_Gepard.png",
  "/stickers/Organized_Stickers/Gepard/Gepard.png",
  "/stickers/Organized_Stickers/Guinaifen/Guinaifen 1.png",
  "/stickers/Organized_Stickers/Guinaifen/Guinaifen 2.png",
  "/stickers/Organized_Stickers/Guinaifen/Guinaifen 3.png",
  "/stickers/Organized_Stickers/Guinaifen/Pom-Pom Gallery _ Jolted Awake From a Winter Dream_Guinaifen 1.png",
  "/stickers/Organized_Stickers/Guinaifen/Pom-Pom Gallery _ Jolted Awake From a Winter Dream_Guinaifen 2.png",
  "/stickers/Organized_Stickers/Hanu/Hanu.png",
  "/stickers/Organized_Stickers/Hanya/Hanya 1.png",
  "/stickers/Organized_Stickers/Hanya/Hanya 2.png",
  "/stickers/Organized_Stickers/Hanya/Hanya 3.png",
  "/stickers/Organized_Stickers/Herta/4_Herta.png",
  "/stickers/Organized_Stickers/Herta/Herta.png",
  "/stickers/Organized_Stickers/Herta/Pom-Pom Gallery _ Crown of the Mundane and Divine_Herta.png",
  "/stickers/Organized_Stickers/Himeko/6_Himeko.png",
  "/stickers/Organized_Stickers/Himeko/Himeko.png",
  "/stickers/Organized_Stickers/Hook/5_Hook.png",
  "/stickers/Organized_Stickers/Hook/Hook.png",
  "/stickers/Organized_Stickers/Huohuo/Huohuo 1.png",
  "/stickers/Organized_Stickers/Huohuo/Huohuo 2.png",
  "/stickers/Organized_Stickers/Huohuo/Huohuo 3.png",
  "/stickers/Organized_Stickers/Huohuo/Huohuo 4.png",
  "/stickers/Organized_Stickers/Huohuo (Tail)/Tail.png",
  "/stickers/Organized_Stickers/Jade/Jade 1.png",
  "/stickers/Organized_Stickers/Jade/Jade 2.png",
  "/stickers/Organized_Stickers/Jade/Jade 3.png",
  "/stickers/Organized_Stickers/Jade/Jade 4.png",
  "/stickers/Organized_Stickers/Jiaoqiu/Jiaoqiu 1.png",
  "/stickers/Organized_Stickers/Jiaoqiu/Jiaoqiu 2.png",
  "/stickers/Organized_Stickers/Jiaoqiu/Jiaoqiu 3.png",
  "/stickers/Organized_Stickers/Jiaoqiu/Jiaoqiu 4.png",
  "/stickers/Organized_Stickers/Jing Yuan/Jing Yuan 1.png",
  "/stickers/Organized_Stickers/Jing Yuan/Jing Yuan 2.png",
  "/stickers/Organized_Stickers/Jingliu/Jingliu 1.png",
  "/stickers/Organized_Stickers/Jingliu/Jingliu 2.png",
  "/stickers/Organized_Stickers/Jingliu/Jingliu 3.png",
  "/stickers/Organized_Stickers/Jingliu/Jingliu 4.png",
  "/stickers/Organized_Stickers/Kafka/8_Kafka.png",
  "/stickers/Organized_Stickers/Kafka/Kafka 1.png",
  "/stickers/Organized_Stickers/Kafka/Kafka 2.png",
  "/stickers/Organized_Stickers/Kafka/Kafka 3.png",
  "/stickers/Organized_Stickers/Kafka/Kafka 4.png",
  "/stickers/Organized_Stickers/Kakavasha/Kakavasha.png",
  "/stickers/Organized_Stickers/Lingsha/Lingsha 1.png",
  "/stickers/Organized_Stickers/Lingsha/Lingsha 2.png",
  "/stickers/Organized_Stickers/Lingsha/Lingsha 3.png",
  "/stickers/Organized_Stickers/Lingsha/Lingsha 4.png",
  "/stickers/Organized_Stickers/Luka/Luka 1.png",
  "/stickers/Organized_Stickers/Luka/Luka 2.png",
  "/stickers/Organized_Stickers/Luka/Luka 3.png",
  "/stickers/Organized_Stickers/Luocha/Luocha.png",
  "/stickers/Organized_Stickers/Lynx/Lynx 1.png",
  "/stickers/Organized_Stickers/Lynx/Lynx 2.png",
  "/stickers/Organized_Stickers/Lynx/Lynx 3.png",
  "/stickers/Organized_Stickers/March 7th/March 7th 1.png",
  "/stickers/Organized_Stickers/March 7th/March 7th 2.png",
  "/stickers/Organized_Stickers/March 7th/March 7th 3.png",
  "/stickers/Organized_Stickers/March 7th/March 7th.png",
  "/stickers/Organized_Stickers/March 7th/March 7th_1.png",
  "/stickers/Organized_Stickers/March 7th/March 7th_10.png",
  "/stickers/Organized_Stickers/March 7th/March 7th_11.png",
  "/stickers/Organized_Stickers/March 7th/March 7th_12.png",
  "/stickers/Organized_Stickers/March 7th/March 7th_13.png",
  "/stickers/Organized_Stickers/March 7th/March 7th_14.png",
  "/stickers/Organized_Stickers/March 7th/March 7th_15.png",
  "/stickers/Organized_Stickers/March 7th/March 7th_16.png",
  "/stickers/Organized_Stickers/March 7th/March 7th_2.png",
  "/stickers/Organized_Stickers/March 7th/March 7th_3.png",
  "/stickers/Organized_Stickers/March 7th/March 7th_4.png",
  "/stickers/Organized_Stickers/March 7th/March 7th_5.png",
  "/stickers/Organized_Stickers/March 7th/March 7th_6.png",
  "/stickers/Organized_Stickers/March 7th/March 7th_7.png",
  "/stickers/Organized_Stickers/March 7th/March 7th_8.png",
  "/stickers/Organized_Stickers/March 7th/March 7th_9.png",
  "/stickers/Organized_Stickers/Mikhail/Mikhail.png",
  "/stickers/Organized_Stickers/Misha/Misha 1.png",
  "/stickers/Organized_Stickers/Misha/Misha 2.png",
  "/stickers/Organized_Stickers/Misha/Misha 3.png",
  "/stickers/Organized_Stickers/Moze/Moze 1.png",
  "/stickers/Organized_Stickers/Moze/Moze 2.png",
  "/stickers/Organized_Stickers/Moze/Moze 3.png",
  "/stickers/Organized_Stickers/Mr. Reca/Mr. Reca.png",
  "/stickers/Organized_Stickers/Natasha/Natasha.png",
  "/stickers/Organized_Stickers/Origami Bird/Origami Bird.png",
  "/stickers/Organized_Stickers/Other/Other.png",
  "/stickers/Organized_Stickers/Pela/12_Pela.png",
  "/stickers/Organized_Stickers/Pela/Pela.png",
  "/stickers/Organized_Stickers/Peppy/Peppy.png",
  "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 1.png",
  "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 10.png",
  "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 2.png",
  "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 3.png",
  "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 4.png",
  "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 5.png",
  "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 6.png",
  "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 7.png",
  "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 8.png",
  "/stickers/Organized_Stickers/Pom-Pom/July 2023 Edition_Pom-Pom 9.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 1.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 10.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 11.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 12.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 13.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 14.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 15.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 16.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 2.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 3.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 4.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 5.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 6.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 7.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 8.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom 9.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom Stickers Set 1_Pom-Pom 1.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom Stickers Set 1_Pom-Pom 2.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom Stickers Set 1_Pom-Pom 3.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom Stickers Set 1_Pom-Pom 4.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom Stickers Set 1_Pom-Pom 5.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom Stickers Set 1_Pom-Pom 6.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom Stickers Set 1_Pom-Pom 7.png",
  "/stickers/Organized_Stickers/Pom-Pom/Pom-Pom.png",
  "/stickers/Organized_Stickers/Qing Que/Qing Que.png",
  "/stickers/Organized_Stickers/Qing Que/Qingque.png",
  "/stickers/Organized_Stickers/Raccoon/Raccoon 1.png",
  "/stickers/Organized_Stickers/Raccoon/Raccoon 2.png",
  "/stickers/Organized_Stickers/Raccoon/Raccoon 3.png",
  "/stickers/Organized_Stickers/Rappa/Rappa 1.png",
  "/stickers/Organized_Stickers/Rappa/Rappa 2.png",
  "/stickers/Organized_Stickers/Rappa/Rappa 3.png",
  "/stickers/Organized_Stickers/Rappa/Rappa 4.png",
  "/stickers/Organized_Stickers/Robin/Robin 1.png",
  "/stickers/Organized_Stickers/Robin/Robin 2.png",
  "/stickers/Organized_Stickers/Robin/Robin 3.png",
  "/stickers/Organized_Stickers/Robin/Robin 4.png",
  "/stickers/Organized_Stickers/Robin/Robin.png",
  "/stickers/Organized_Stickers/Ruan Mei/Ruan Mei 1.png",
  "/stickers/Organized_Stickers/Ruan Mei/Ruan Mei 2.png",
  "/stickers/Organized_Stickers/Ruan Mei/Ruan Mei 3.png",
  "/stickers/Organized_Stickers/Ruan Mei/Ruan Mei 4.png",
  "/stickers/Organized_Stickers/Sampo/13_Sampo.png",
  "/stickers/Organized_Stickers/Sampo/Pom-Pom Gallery _ If One Dreams At Midnight_Sampo.png",
  "/stickers/Organized_Stickers/Sampo/Pom-Pom Gallery _ Jolted Awake From a Winter Dream_Sampo.png",
  "/stickers/Organized_Stickers/Sampo/Sampo.png",
  "/stickers/Organized_Stickers/Screwllum/Screwllum.png",
  "/stickers/Organized_Stickers/Serval/15_Serval.png",
  "/stickers/Organized_Stickers/Serval/Serval.png",
  "/stickers/Organized_Stickers/Silver Wolf/16_Silver Wolf.png",
  "/stickers/Organized_Stickers/Slumbernana Monkey/Slumbernana Monkey 1.png",
  "/stickers/Organized_Stickers/Slumbernana Monkey/Slumbernana Monkey 2.png",
  "/stickers/Organized_Stickers/Slumbernana Monkey/Slumbernana Monkey 3.png",
  "/stickers/Organized_Stickers/Sparkle/Pom-Pom Gallery _ If One Dreams At Midnight_Sparkle 1.png",
  "/stickers/Organized_Stickers/Sparkle/Pom-Pom Gallery _ If One Dreams At Midnight_Sparkle 2.png",
  "/stickers/Organized_Stickers/Sparkle/Sparkle 1.png",
  "/stickers/Organized_Stickers/Sparkle/Sparkle 2.png",
  "/stickers/Organized_Stickers/Sparkle/Sparkle 3.png",
  "/stickers/Organized_Stickers/Sparkle/Sparkle 4.png",
  "/stickers/Organized_Stickers/Stelle Harmony/Stelle Harmony.png",
  "/stickers/Organized_Stickers/Sunday/Sunday.png",
  "/stickers/Organized_Stickers/Sushang/Pom-Pom Gallery - Finest Duel Under the Pristine Blue Set 16_Sushang.png",
  "/stickers/Organized_Stickers/Sushang/Pom-Pom Gallery _ Jolted Awake From a Winter Dream_Sushang.png",
  "/stickers/Organized_Stickers/Sushang/Pom-Pom Gallery_ Final Closed Beta_Sushang.png",
  "/stickers/Organized_Stickers/Sushang/Sushang.png",
  "/stickers/Organized_Stickers/Talisman/Talisman.png",
  "/stickers/Organized_Stickers/Tingyun/Pom-Pom Gallery_ Final Closed Beta_Tingyun.png",
  "/stickers/Organized_Stickers/Tingyun/Tingyun.png",
  "/stickers/Organized_Stickers/Topaz/Topaz 1.png",
  "/stickers/Organized_Stickers/Topaz/Topaz 2.png",
  "/stickers/Organized_Stickers/Topaz/Topaz 3.png",
  "/stickers/Organized_Stickers/Topaz/Topaz 4.png",
  "/stickers/Organized_Stickers/Topaz/Topaz.png",
  "/stickers/Organized_Stickers/Trailblazer (Caelus)/10_Male MC.png",
  "/stickers/Organized_Stickers/Trailblazer (Caelus)/Caelus.png",
  "/stickers/Organized_Stickers/Trailblazer (Caelus)/Trailblazer_male.png",
  "/stickers/Organized_Stickers/Trailblazer (Stelle)/11_Female MC.png",
  "/stickers/Organized_Stickers/Trailblazer (Stelle)/Stelle.png",
  "/stickers/Organized_Stickers/Trailblazer (Stelle)/Trailblazer_female.png",
  "/stickers/Organized_Stickers/Trash Can/Trash Can.png",
  "/stickers/Organized_Stickers/Tuskpir/Tuskpir.png",
  "/stickers/Organized_Stickers/Welt/14_Welt.png",
  "/stickers/Organized_Stickers/Welt/Welt.png",
  "/stickers/Organized_Stickers/Xueyi/Xueyi 1.png",
  "/stickers/Organized_Stickers/Xueyi/Xueyi 2.png",
  "/stickers/Organized_Stickers/Xueyi/Xueyi 3.png",
  "/stickers/Organized_Stickers/Yanqing/Yanqing 1.png",
  "/stickers/Organized_Stickers/Yanqing/Yanqing 2.png",
  "/stickers/Organized_Stickers/Yanqing/Yanqing.png",
  "/stickers/Organized_Stickers/Young Jing Yuan/Young Jing Yuan.png",
  "/stickers/Organized_Stickers/Yukong/Pom-Pom Gallery_ Final Closed Beta_Yukong.png",
  "/stickers/Organized_Stickers/Yukong/Yukong.png",
  "/stickers/Organized_Stickers/Yunli/Yunli 1.png",
  "/stickers/Organized_Stickers/Yunli/Yunli 2.png",
  "/stickers/Organized_Stickers/Yunli/Yunli 3.png",
  "/stickers/Organized_Stickers/Yunli/Yunli 4.png"
];
